[project]
name = "forex-dbt"
version = "0.1.0"
description = "Downloader and dbt project for forex rates."
readme = "../README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-bigquery>=1.10.2",
    "dlt[bigquery]>=0.4.0",
    "google-cloud-bigquery>=3.26.0",
    "requests>=2.32.5",
]
